openapi: 3.0.0
info:
  title: nodejs-sequelize-spatial
  version: 0.0.1
  description: |
    shp 업로드 및 조회 API
     - nodejs-sequelize-spatial
  termsOfService: 'https://songjang.tistory.com'
  contact:
    email: sbjang123456@gmail.com
  license:
    name: songjang.co.kr
    url: 'https://songjang.tistory.com'
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'http://localhost:3000'
tags:
  - name: shp
    description: shp upload 및 geojosn 조회
paths:
  /shp/ctprvn:
    post:
      tags:
        - shp
      summary: 시도경계 shp 업로드
#      operationId: getTest
      description: |
        시경계 shp 업로드
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                shapeFile:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '200':
          description: ctprvn shp upload success!
        '500':
          description: ctprvn shp upload fail!
  /shp/sig:
    post:
      tags:
        - shp
      summary: 시군구경계 shp 업로드
      #      operationId: getTest
      description: |
        시군구경계 shp 업로드
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                shapeFile:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '200':
          description: sig shp upload success!
        '500':
          description: sig shp upload fail!
#components:
#  schemas:
#    Response:
#      type: object
#      properties:
#        success:
#          type: boolean
#        code:
#          type: integer
#          format: int32
#        msg:
#          type: string
#        result:
#          type: object